/**
 * Declaring the packages a migrated workspace's builder targets name.
 *
 * An Angular workspace runs a target by resolving the package named on the left
 * of the colon in its `builder` string and asking it for the builder named on
 * the right. The package has to be in the manifest for that resolution to
 * happen; nothing installs it implicitly.
 *
 * A workspace generated by Angular CLI 1.x has no such declaration and never
 * needed one: the CLI of that era carried its own webpack build inside the
 * `@angular/cli` package and its workspace document names no builder at all.
 * Lifting that document to the modern schema writes builder strings into it for
 * the first time, and a manifest that still looks like the era one then names
 * every target the workspace can run and provides none of them. The build fails
 * at target resolution — before a single application file is read — with a
 * message about a builder package rather than about the application.
 *
 * This capability closes that hole and nothing else. It reads the builder
 * strings out of the *migrated* workspace document, so a target the workspace
 * migration removed contributes no declaration, and it writes each package the
 * cell has a range for into `devDependencies` at that range. A builder package
 * the cell has no range for is reported by name and left undeclared: picking a
 * version for a package no table covers would be a guess about a toolchain, and
 * a guessed toolchain version is exactly the kind of silent decision a migration
 * record exists to rule out.
 */

import {
	alignedVersionRange,
	compareStrings,
	type AngularTargetCell,
} from './angular-target-cell.ts';

export type BuilderPackageDeclaration = Readonly<{
	field: 'devDependencies';
	name: string;
	range: string;
	/** The builder strings in the workspace that asked for this package. */
	builders: readonly string[];
	reason: string;
}>;

export type BuilderPackageDeclarations = Readonly<{
	manifest: Readonly<Record<string, unknown>>;
	declarations: readonly BuilderPackageDeclaration[];
	unhandled: readonly string[];
}>;

/** The package half of a builder string: everything left of the last colon. */
export function builderPackageName(builder: string): string | null {
	const separator = builder.lastIndexOf(':');
	if (separator <= 0 || separator === builder.length - 1) return null;
	return builder.slice(0, separator);
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Every builder string a workspace document names, keyed by the package it
 * resolves, in the order the packages sort.
 *
 * The walk is structural: `projects.<name>.architect.<target>.builder`, which is
 * where the modern schema puts them. A document that is not JSON, or that has no
 * projects, contributes nothing — the migration that parses it properly refuses
 * it with its own diagnosable error, and reporting the same defect twice under
 * two names helps nobody.
 */
export function workspaceBuilderPackages(
	workspaceConfig: string,
): Readonly<Record<string, readonly string[]>> {
	let document: unknown;
	try {
		document = JSON.parse(workspaceConfig) as unknown;
	} catch {
		return Object.freeze({});
	}
	if (!isRecord(document)) return Object.freeze({});
	const projects = document['projects'];
	if (!isRecord(projects)) return Object.freeze({});
	const found = new Map<string, Set<string>>();
	for (const project of Object.values(projects)) {
		if (!isRecord(project)) continue;
		const architect = project['architect'];
		if (!isRecord(architect)) continue;
		for (const target of Object.values(architect)) {
			if (!isRecord(target)) continue;
			const builder = target['builder'];
			if (typeof builder !== 'string') continue;
			const name = builderPackageName(builder);
			if (name === null) continue;
			const builders = found.get(name) ?? new Set<string>();
			builders.add(builder);
			found.set(name, builders);
		}
	}
	const packages: Record<string, readonly string[]> = {};
	for (const name of [...found.keys()].sort(compareStrings))
		packages[name] = Object.freeze([...(found.get(name) ?? [])].sort(compareStrings));
	return Object.freeze(packages);
}

function declaredRanges(manifest: Readonly<Record<string, unknown>>): ReadonlySet<string> {
	const names = new Set<string>();
	for (const field of [
		'dependencies',
		'devDependencies',
		'peerDependencies',
		'optionalDependencies',
	]) {
		const record = manifest[field];
		if (!isRecord(record)) continue;
		for (const name of Object.keys(record)) names.add(name);
	}
	return names;
}

/**
 * Declare every builder package the migrated workspace names and the manifest
 * does not already carry.
 *
 * A package already declared anywhere in the manifest is left exactly as it is:
 * this capability closes a hole, it does not re-align a range another capability
 * already decided.
 */
export function declareBuilderPackages(
	manifest: Readonly<Record<string, unknown>>,
	workspaceConfig: string,
	cell: AngularTargetCell,
): BuilderPackageDeclarations {
	const declarations: BuilderPackageDeclaration[] = [];
	const unhandled: string[] = [];
	const already = declaredRanges(manifest);
	const packages = workspaceBuilderPackages(workspaceConfig);
	const next: Record<string, unknown> = { ...manifest };
	const devDependencies: Record<string, string> = isRecord(manifest['devDependencies'])
		? { ...(manifest['devDependencies'] as Record<string, string>) }
		: {};
	for (const [name, builders] of Object.entries(packages)) {
		if (already.has(name)) continue;
		const range = alignedVersionRange(name, cell);
		if (range === null) {
			unhandled.push(
				`the migrated workspace runs ${builders.join(', ')}, whose package ${name} the ` +
					`manifest does not declare and ${cell.id} has no range for, so it was left ` +
					`undeclared rather than pinned to a guessed version`,
			);
			continue;
		}
		devDependencies[name] = range;
		declarations.push({
			field: 'devDependencies',
			name,
			range,
			builders,
			reason:
				`the migrated workspace runs ${builders.join(', ')}, and a target resolves its ` +
				`builder through the package named to the left of the colon; the era workspace ` +
				`named no builder at all, so nothing declared it`,
		});
	}
	if (declarations.length === 0)
		return Object.freeze({
			manifest,
			declarations: Object.freeze([]),
			unhandled: Object.freeze(unhandled),
		});
	const ordered: Record<string, string> = {};
	for (const name of Object.keys(devDependencies).sort(compareStrings))
		ordered[name] = devDependencies[name] as string;
	next['devDependencies'] = ordered;
	return Object.freeze({
		manifest: Object.freeze(next),
		declarations: Object.freeze(declarations),
		unhandled: Object.freeze(unhandled),
	});
}
