import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { Readable } from 'node:stream';
import { afterEach, describe, expect, test } from 'vitest';
import { join } from 'pathe';
import {
	REACT_GRAPHIQL_CONSENT,
	analyzeGraphiQLYarnLock,
	assertGraphiQLAccessReplay,
	assertGraphiQLArchiveEntries,
	assertGraphiQLPackageEdges,
	assertGraphiQLTreeRows,
	assertGraphiQLUrl,
	createGraphiQLAttemptParent,
	collectGraphiQLIdentityStream,
	collectGraphiQLResponseBoundary,
	parseGraphiQLLauncher,
} from '../src/fixture/react-graphiql-013-ingest.ts';

const originalMode = process.env.VERSIONLESS_NETWORK_MODE;
const originalConsent = process.env.VERSIONLESS_CONSENT_ID;
const originalOffline = process.env.NPM_CONFIG_OFFLINE;

afterEach(() => {
	if (originalMode === undefined) delete process.env.VERSIONLESS_NETWORK_MODE;
	else process.env.VERSIONLESS_NETWORK_MODE = originalMode;
	if (originalConsent === undefined) delete process.env.VERSIONLESS_CONSENT_ID;
	else process.env.VERSIONLESS_CONSENT_ID = originalConsent;
	if (originalOffline === undefined) delete process.env.NPM_CONFIG_OFFLINE;
	else process.env.NPM_CONFIG_OFFLINE = originalOffline;
});

describe('GraphiQL 0.13 transactional ingest', () => {
	test('uses one production launcher graph and reports offline smoke without requests', () => {
		process.env.VERSIONLESS_NETWORK_MODE = 'offline';
		process.env.NPM_CONFIG_OFFLINE = 'true';
		delete process.env.VERSIONLESS_CONSENT_ID;
		expect(
			parseGraphiQLLauncher(['--launcher-smoke', '--consent-id', REACT_GRAPHIQL_CONSENT]),
		).toBe('launcher-smoke');
		process.env.VERSIONLESS_NETWORK_MODE = 'consented';
		process.env.VERSIONLESS_CONSENT_ID = REACT_GRAPHIQL_CONSENT;
		expect(parseGraphiQLLauncher(['--acquire', '--consent-id', REACT_GRAPHIQL_CONSENT])).toBe(
			'acquire',
		);
		process.env.VERSIONLESS_NETWORK_MODE = 'offline';
		expect(() =>
			parseGraphiQLLauncher(['--acquire', '--consent-id', REACT_GRAPHIQL_CONSENT]),
		).toThrow('one-shot consent');
	});

	test('creates every nested attempt parent before an exclusive write', async () => {
		const temporary = await mkdtemp(join(tmpdir(), 'versionless-t577-parent-'));
		try {
			const attempt = join(temporary, 'deep/t577/transaction/attempt.json');
			await createGraphiQLAttemptParent(attempt);
			await writeFile(attempt, '{"invoked":true}\n', { flag: 'wx' });
			expect(await readFile(attempt, 'utf8')).toBe('{"invoked":true}\n');
			await expect(writeFile(attempt, 'overwrite', { flag: 'wx' })).rejects.toThrow();
		} finally {
			await rm(temporary, { recursive: true, force: true });
		}
	});

	test('parses and strengthens a bounded Yarn-v1 closure without moving refs', () => {
		const stanzas = Array.from({ length: 300 }, (_, index) => {
			const sha1 = index.toString(16).padStart(40, '0');
			const integrity = Buffer.alloc(64, index % 256).toString('base64');
			return `package-${index}@^1.0.0:\n  version "1.0.${index}"\n  resolved "https://registry.yarnpkg.com/package-${index}/-/package-${index}-1.0.${index}.tgz#${sha1}"\n  integrity sha512-${integrity}\n`;
		});
		const result = analyzeGraphiQLYarnLock(
			Buffer.from(
				`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n${stanzas.join('\n')}`,
			),
		);
		expect(result.artifacts).toHaveLength(300);
		expect(result.placements).toBe(300);
		expect(result.digest).toHaveLength(64);
		expect(result.artifacts[0]?.url).toBe(
			'https://registry.yarnpkg.com/package-0/-/package-0-1.0.0.tgz',
		);
	});

	test('allows only exact credential-free HTTPS sources and safe single-root archives', () => {
		const exact = 'https://cdn.jsdelivr.net/es6-promise/4.0.5/es6-promise.auto.min.js';
		const allowed = new Set([exact]);
		expect(() => assertGraphiQLUrl(exact, allowed)).not.toThrow();
		for (const changed of [
			'http://cdn.jsdelivr.net/es6-promise/4.0.5/es6-promise.auto.min.js',
			'https://user@cdn.jsdelivr.net/es6-promise/4.0.5/es6-promise.auto.min.js',
			`${exact}?moving=true`,
			'https://example.com/asset.js',
		])
			expect(() => assertGraphiQLUrl(changed, allowed)).toThrow('outside exact consent');
		expect(() =>
			assertGraphiQLArchiveEntries(
				Array.from({ length: 285 }, (_, index) => `graphiql-source/file-${index}.js`),
			),
		).not.toThrow();
		expect(() =>
			assertGraphiQLArchiveEntries([
				...Array.from({ length: 284 }, (_, index) => `graphiql-source/file-${index}.js`),
				'../escape',
			]),
		).toThrow('unsafe');
		const rows = Array.from({ length: 285 }, (_, index) => ({
			path: `path/file-${index}.js`,
			mode: '100644',
			type: 'blob',
			sha: index.toString(16).padStart(40, '0'),
			size: index,
		}));
		expect(() => assertGraphiQLTreeRows(rows)).not.toThrow();
		expect(() =>
			assertGraphiQLTreeRows([{ ...rows[0]!, mode: '120000' }, ...rows.slice(1)]),
		).toThrow('mode or size differs');
	});

	test('keeps React15 CDN provenance edges distinct from React18 target edges', () => {
		expect(() =>
			assertGraphiQLPackageEdges('react', '15.4.2', {
				fbjs: '^0.8.4',
				'loose-envify': '^1.1.0',
				'object-assign': '^4.1.1',
			}),
		).not.toThrow();
		expect(() =>
			assertGraphiQLPackageEdges('react', '18.3.1', { 'loose-envify': '^1.1.0' }),
		).not.toThrow();
		expect(() =>
			assertGraphiQLPackageEdges('react', '15.4.2', { 'loose-envify': '^1.1.0' }),
		).toThrow('dependency edges differ');
		expect(() =>
			assertGraphiQLPackageEdges('react', '18.3.1', {
				fbjs: '^0.8.4',
				'loose-envify': '^1.1.0',
				'object-assign': '^4.1.1',
			}),
		).toThrow('dependency edges differ');
	});

	test('counts failed identity-stream bytes and rejects oversized or errored streams', async () => {
		let oversizedWire = 0;
		await expect(
			collectGraphiQLIdentityStream(
				Readable.from([Buffer.alloc(4), Buffer.alloc(5)]),
				8,
				(size) => {
					oversizedWire += size;
				},
			),
		).rejects.toThrow('byte cap exceeded');
		expect(oversizedWire).toBe(9);
		let failedWire = 0;
		const failed = new Readable({
			read() {
				this.push(Buffer.alloc(3));
				this.destroy(new Error('synthetic stream failure'));
			},
		});
		await expect(
			collectGraphiQLIdentityStream(failed, 8, (size) => {
				failedWire += size;
			}),
		).rejects.toThrow('synthetic stream failure');
		expect(failedWire).toBe(3);
	});

	test('bounded-drains and counts non-200, redirect, cookie and encoding response bodies', async () => {
		for (const boundary of ['non-200', 'redirect', 'cookie', 'content-encoding']) {
			let wire = 0;
			await expect(
				collectGraphiQLResponseBoundary(
					Readable.from([Buffer.from(boundary), Buffer.from('-body')]),
					128,
					false,
					(size) => {
						wire += size;
					},
				),
			).rejects.toThrow('response boundary differs');
			expect(wire).toBe(Buffer.byteLength(`${boundary}-body`));
		}
	});

	test('rejects resealed-style access ledger URL, ordinal, digest and byte-total drift', () => {
		const urls = [
			'https://api.github.com/repos/graphql/graphiql/git/commits/f997c204e4d4bb0be4d0e2e136471dc62b807ddd',
			'https://registry.npmjs.org/react/18.3.1',
			'https://cdn.jsdelivr.net/react/15.4.2/react.min.js',
		];
		const ledger = urls.map((url, index) => ({
			ordinal: index + 1,
			origin: index === 0 ? 'github' : index === 1 ? 'registry' : 'cdn',
			url,
			result: 'accepted',
			wireBytes: 10 + index,
			decodedBytes: 10 + index,
			sha256: 'a'.repeat(64),
			sha512: 'b'.repeat(64),
		}));
		const totals = { github: 10, registry: 11, cdn: 12 };
		expect(() =>
			assertGraphiQLAccessReplay({
				ledger,
				expectedUrls: urls,
				wire: totals,
				decoded: totals,
			}),
		).not.toThrow();
		for (const mutate of [
			(rows: Array<Record<string, unknown>>) => (rows[0]!.ordinal = 2),
			(rows: Array<Record<string, unknown>>) => (rows[1]!.sha256 = 'short'),
			(rows: Array<Record<string, unknown>>) => (rows[2]!.decodedBytes = 11),
			(rows: Array<Record<string, unknown>>) => (rows[0]!.url = urls[1]),
		]) {
			const changed = structuredClone(ledger);
			mutate(changed);
			expect(() =>
				assertGraphiQLAccessReplay({
					ledger: changed,
					expectedUrls: urls,
					wire: totals,
					decoded: totals,
				}),
			).toThrow();
		}
	});
});
