/**
 * The record of the offline-faithful rebuild: the migrated super-productivity
 * lane with the Angular 16 font inliner turned off.
 *
 * u21 read `app/dist/index.html` — the document u18j published — and found
 * forty-five `@font-face` rules that exist in no input, which is the body of the
 * Roboto stylesheet the builder fetched from `fonts.googleapis.com` while the
 * build was running. u21 established that from the document alone and said so:
 * it observed no build and captured no traffic. This round observes the build.
 *
 * Every number here is read at the moment the record is written: three build
 * logs, three egress logs, three emitted inventories — the two this round
 * produced and the superseded one, which is still on disk — the source and
 * emitted documents, the emitted runtime chunk and the emitted service-worker
 * manifest. The control build is part of the evidence rather than a rehearsal:
 * it is the same workspace u18j built, run under the same guard, and it goes red
 * on the fetch. A green control would have meant the guard was measuring
 * nothing.
 *
 * No witness work is done here and none is claimed. The deliverable is the
 * corrected lane and the record of it; the browser proof for this vertical
 * resumes against these bytes.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import {
	charIn,
	charNotIn,
	createRegExp,
	exactly,
	global as globalFlag,
	oneOrMore,
} from 'magic-regexp';
import * as path from 'pathe';
import { canonical, sha256 } from './angular-factoriolab-migration-run.ts';
import {
	inventoryOf,
	sealRecord,
	verifySealedRecord,
	type DistEntry,
	type SealedRecord,
} from './angular-factoriolab-build-lanes-run.ts';
import { CONSENT, EVIDENCE_DIRECTORY } from './angular-super-productivity-lanes-run.ts';
import { APPLIED_TREE, STAGE_DIRECTORY } from './angular-super-productivity-apply-run.ts';
import {
	CANONICAL_ROOT,
	REPEATED_ROOT,
	UNIT,
	type FontRound,
} from './angular-super-productivity-u23-font-run.ts';

export const FONT_LANE_FILE = 'u23-offline-font-lane.json';
/** The output root u18j published, kept on disk and read here as the superseded lane. */
export const SUPERSEDED_ROOT = 'app/dist';
/** The record this round supersedes, and the u21 reading it answers. */
export const SUPERSEDED_RECORD = 'u18j-worker-chunks-parity.json';
export const LOCALITY_FINDING = Object.freeze({
	record: 'evidence/runs/angular-super-productivity-v2-13-15/u21-font-inline-locality.json',
	digest: '7f7dbf94127e57ca79029a6c93a74ffd61f2ec1347e4ce3bf25b55bdbee5ff2a',
});

const LINK_HREF = createRegExp(
	exactly('<link')
		.and(oneOrMore(charNotIn('>')))
		.and('href="')
		.and(oneOrMore(charNotIn('"')).groupedAs('href'))
		.and('"'),
	[globalFlag],
);

/** Every `<link>` href in a document, in document order. */
export function linkHrefs(html: string): readonly string[] {
	return Object.freeze(
		[...html.matchAll(LINK_HREF)].map((match) => match.groups['href'] as string),
	);
}

/** How many `@font-face` rules a document carries in its own bytes. */
export function fontFaceRules(html: string): number {
	return html.split('@font-face').length - 1;
}

/** An inventory as a path → digest map, for set comparisons. */
function digestsOf(inventory: readonly DistEntry[]): ReadonlyMap<string, string> {
	return new Map(inventory.map((entry) => [entry.path, entry.sha256]));
}

/**
 * A name segment that is nothing but a run of at least eight hex digits, which
 * is what the Angular CLI stamps a content hash into a file name as.
 */
const HEX_SEGMENT = createRegExp(
	charIn('0123456789abcdef').times.between(8, 40).at.lineStart().at.lineEnd(),
);

/**
 * An emitted file name with its content hashes elided — every `.<hex>` segment
 * removed wherever it appears in the name.
 *
 * This is u18j's own elision rather than the `emissionPointOf` this cell uses
 * for cross-lane parity, whose hash pattern only reaches a hash sitting
 * immediately before the final extension and therefore leaves
 * `main.<hash>.js.map` alone. Comparing a census across a
 * rebuild has to elide the map files too, because a chunk whose content hash
 * moves renames its map with it.
 */
export function logicalNameOf(file: string): string {
	return file
		.split('/')
		.map((segment) =>
			segment
				.split('.')
				.filter((part) => !HEX_SEGMENT.test(part))
				.join('.'),
		)
		.join('/');
}

/**
 * The reading that says whether the difference between two emitted chunks is
 * this cell's recorded Sass nondeterminism rather than something this round did.
 *
 * The era baseline chased that instability to one line — a `@keyframes bang`
 * whose box-shadow list is generated by unseeded Sass `random()` — and the only
 * honest way to attribute a moved content hash to it is to walk to the first
 * byte where the two chunks disagree and read what is written there.
 */
export function firstDifference(
	left: string,
	right: string,
): Readonly<{ offset: number; leftExcerpt: string; rightExcerpt: string; insideBangKeyframes: boolean }> | null {
	const shortest = Math.min(left.length, right.length);
	let offset = 0;
	while (offset < shortest && left[offset] === right[offset]) offset += 1;
	if (offset === shortest && left.length === right.length) return null;
	const window = 96;
	const preceding = left.slice(Math.max(0, offset - window), offset);
	return Object.freeze({
		offset,
		leftExcerpt: left.slice(offset, offset + window),
		rightExcerpt: right.slice(offset, offset + window),
		insideBangKeyframes: preceding.includes('_bang{') && preceding.includes('box-shadow'),
	});
}

export async function buildFontLaneRecord(): Promise<SealedRecord> {
	const round = JSON.parse(
		await readFile(path.join(STAGE_DIRECTORY, 'u23-font-round.json'), 'utf8'),
	) as FontRound;
	const first = await inventoryOf(path.join(STAGE_DIRECTORY, CANONICAL_ROOT));
	const second = await inventoryOf(path.join(STAGE_DIRECTORY, REPEATED_ROOT));
	const superseded = await inventoryOf(path.join(STAGE_DIRECTORY, SUPERSEDED_ROOT));
	const identical = canonical(first) === canonical(second);
	const firstDigests = digestsOf(first);
	const secondDigests = digestsOf(second);
	const supersededDigests = digestsOf(superseded);
	const differingAcrossRuns = first
		.filter((entry) => secondDigests.get(entry.path) !== entry.sha256)
		.map((entry) => entry.path);
	const namesUnchanged = [...firstDigests.keys()].filter((name) => supersededDigests.has(name));
	const changedAgainstSuperseded = namesUnchanged.filter(
		(name) => firstDigests.get(name) !== supersededDigests.get(name),
	);
	const logical = (inventory: readonly DistEntry[]): readonly string[] =>
		Object.freeze([...new Set(inventory.map((entry) => logicalNameOf(entry.path)))].sort());
	const logicalNow = logical(first);
	const logicalThen = logical(superseded);
	const censusHolds =
		first.length === superseded.length && canonical(logicalNow) === canonical(logicalThen);

	/**
	 * The two runs' service-worker manifests, compared key by key, because
	 * "deterministic modulo a clock field" is a claim about which key moved and
	 * has to be read rather than asserted.
	 */
	const manifestOf = async (root: string): Promise<Readonly<Record<string, unknown>>> =>
		JSON.parse(await readFile(path.join(STAGE_DIRECTORY, root, 'ngsw.json'), 'utf8')) as Readonly<
			Record<string, unknown>
		>;
	const firstManifest = await manifestOf(CANONICAL_ROOT);
	const secondManifest = await manifestOf(REPEATED_ROOT);
	const manifestKeysDiffering = [
		...new Set([...Object.keys(firstManifest), ...Object.keys(secondManifest)]),
	]
		.filter((key) => canonical(firstManifest[key]) !== canonical(secondManifest[key]))
		.sort();
	const deterministicModuloClock =
		differingAcrossRuns.length === 0 ||
		(canonical(differingAcrossRuns) === canonical(['ngsw.json']) &&
			canonical(manifestKeysDiffering) === canonical(['timestamp']));

	const sourceIndex = await readFile(path.join(APPLIED_TREE, 'src/index.html'), 'utf8');
	const emittedIndex = await readFile(
		path.join(STAGE_DIRECTORY, CANONICAL_ROOT, 'index.html'),
		'utf8',
	);
	const supersededIndex = await readFile(
		path.join(STAGE_DIRECTORY, SUPERSEDED_ROOT, 'index.html'),
		'utf8',
	);
	const isFontHost = (href: string): boolean => href.includes('fonts.googleapis.com');
	const emittedFontLinks = linkHrefs(emittedIndex).filter(isFontHost);
	const sourceFontLinks = linkHrefs(sourceIndex).filter(isFontHost);

	/**
	 * The worker chunks, found by the emission points u18j published rather than
	 * by a name written here. If the rebuild had dropped one, this list would come
	 * back short rather than come back wrong.
	 */
	const supersededRecord = JSON.parse(
		await readFile(path.join(EVIDENCE_DIRECTORY, SUPERSEDED_RECORD), 'utf8'),
	) as Readonly<{ workerChunks: Readonly<{ emitted: readonly string[] }> }>;
	const workerPoints = new Set(supersededRecord.workerChunks.emitted.map(logicalNameOf));
	const workerChunks = first
		.filter((entry) => workerPoints.has(logicalNameOf(entry.path)))
		.map((entry) => entry.path);
	const runtimeChunk = first.find((entry) => entry.path.startsWith('runtime.'));
	const runtimeSource =
		runtimeChunk === undefined
			? ''
			: await readFile(path.join(STAGE_DIRECTORY, CANONICAL_ROOT, runtimeChunk.path), 'utf8');
	const hashTable = (firstManifest['hashTable'] ?? {}) as Readonly<Record<string, string>>;
	const precached = workerChunks.filter(
		(file) => file.endsWith('.js') && `/${file}` in hashTable,
	);
	/** A chunk is referenced when the runtime's id-to-filename map carries its hash. */
	const contentHashOf = (file: string): string => file.split('.').at(-2) ?? file;
	const referencedByRuntime = workerChunks.filter(
		(file) => file.endsWith('.js') && runtimeSource.includes(contentHashOf(file)),
	);

	/**
	 * The application chunk in each lane, paired by logical name so that a moved
	 * content hash is a renaming to read rather than a file to lose track of.
	 */
	const mainOf = (inventory: readonly DistEntry[]): DistEntry | undefined =>
		inventory.find((entry) => logicalNameOf(entry.path) === 'main.js');
	const supersededMain = mainOf(superseded);
	const currentMain = mainOf(first);
	const sassReading =
		supersededMain === undefined || currentMain === undefined
			? null
			: firstDifference(
					await readFile(path.join(STAGE_DIRECTORY, SUPERSEDED_ROOT, supersededMain.path), 'utf8'),
					await readFile(path.join(STAGE_DIRECTORY, CANONICAL_ROOT, currentMain.path), 'utf8'),
				);

	const supersededBytes = await readFile(
		path.join(EVIDENCE_DIRECTORY, SUPERSEDED_RECORD),
		'utf8',
	);
	const egressFree = round.builds.every((build) => build.egressAttempts.length === 0);
	const green = round.builds.every((build) => build.exitStatus === 0);
	/**
	 * The emitted document writes the same URL the source writes, with `&`
	 * serialised as the entity `&amp;` — which is the document's own escaping and
	 * not a different address. Comparing the two after unescaping that one entity
	 * is what makes "the era font seam is back" a comparison rather than a count.
	 */
	const unescaped = (href: string): string => href.split('&amp;').join('&');
	const emittedFontLinksMatchSource =
		canonical(emittedFontLinks.map(unescaped)) === canonical([...sourceFontLinks]);
	const eraFaithfulSeam =
		fontFaceRules(emittedIndex) === 0 && emittedFontLinksMatchSource && sourceFontLinks.length > 0;

	return sealRecord({
		schemaVersion: 'versionless.angular-super-productivity-offline-font-lane.v1',
		unit: UNIT,
		consentId: CONSENT,
		result:
			green && egressFree && deterministicModuloClock && eraFaithfulSeam && censusHolds
				? 'font-inlining-disabled-build-green-offline-deterministic-modulo-the-clock-and-the-era-font-seam-restored'
				: 'font-inlining-disabled-and-the-lane-did-not-come-back-clean',
		meaning:
			'The Angular 16 browser builder inlines every Google Fonts stylesheet an application links, ' +
			'and it does it by fetching the stylesheet from the font host while the build runs. u18j ' +
			'published a lane built that way without knowing it: forty-five `@font-face` rules that ' +
			'appear in no input, which is the Roboto stylesheet this application links, fetched on the ' +
			'build day. This round turns the inliner off with the landed capability and rebuilds twice, ' +
			'and it measures the fetch rather than reasoning about it: every build here runs under an ' +
			'in-process guard that records and refuses any connection to a non-loopback address. The ' +
			'control build — the workspace exactly as u18j left it — reaches for `fonts.googleapis.com` ' +
			'and dies when it cannot have it. The two builds after the capability make no attempt at ' +
			'all, are green, emit the same 62-artifact census u18j measured with both worker chunks in ' +
			'it, and agree with each other file for file except the one clock field in the generated ' +
			'service-worker manifest. The emitted document links the Roboto stylesheet again and inlines ' +
			'nothing, which is exactly what the era build emitted: the browser fetches it at runtime, ' +
			'and the migrated lane is once more offline-buildable and behaviour-faithful at the same ' +
			'time.',
		answers: LOCALITY_FINDING,
		capability: {
			name: 'font-inlining-disable',
			package: '@versionless/angular',
			module: 'packages/frameworks/angular/src/font-inlining-disable.ts',
			answers:
				"the modern browser builder's `optimization.fonts.inline` default, which is on and which " +
				"the devkit's own schema documents as requiring internet access",
			mechanism:
				'The capability reads two things and nothing else: the builder name, because `:server` ' +
				'declares an `optimization` option with no `fonts` member and would reject the key, and ' +
				'the shape of whatever `optimization` value the workspace declares. A declared `false` is ' +
				'left alone so that turning the inliner off can never switch optimisation on; a declared ' +
				'`true` or an ABSENT option becomes an explicit object carrying the schema\'s own defaults ' +
				'for scripts and styles plus `fonts.inline: false`, because an absent option is the ' +
				"schema's `true` and therefore inlines. Base options are written even when they declare " +
				'nothing; a named configuration is rewritten only when it declares the option itself.',
			driver: 'packages/cli/src/fixture/angular-super-productivity-u23-font-run.ts',
			appliedBy:
				'packages/cli/src/fixture/angular-tiny-translator-u22-font-run.ts, whose workspace ' +
				"application takes the tree as a parameter and is run here against this lane's tree. The " +
				'defect is a builder default rather than a property of an application, so a second copy ' +
				'of the application logic would have been a second thing to keep honest.',
			workspace: round.application.workspace,
			targetsRead: round.application.targetsRead,
			inliningTargets: round.application.inliningTargets,
			sites: round.application.sites,
			declaredDifferences: round.application.declaredDifferences,
			appliedByThisRound: round.application.changed,
		},
		applied: {
			tree: '.versionless/stage/angular-super-productivity-v2-13-15-u18b/app',
			filesChanged: ['angular.json'],
			applicationSourceChanged: false,
			note:
				'One file changed and it is not application source: the workspace. No component, module, ' +
				'template, style, worker or polyfill differs from the tree u18j built, and the emitted ' +
				'bundles below are the ones u18j emitted except where this record says otherwise.',
		},
		egressGuard: {
			state: 'measured-process-scoped-refusal',
			mechanism:
				'Every build this round ran was preloaded with a guard that patches the socket connect ' +
				'every http, https and tls client ends up at and the DNS lookup that precedes it. Each ' +
				'attempt is written to a JSON-lines file with its host and port BEFORE it is refused, so ' +
				'a build that made no attempt and a build whose attempt was refused are distinguishable ' +
				'facts rather than one silent one.',
			source: 'packages/cli/src/fixture/angular-tiny-translator-u22-font-run.ts',
			scope: 'process',
			osWideIsolation: false,
		},
		control: {
			question:
				'Does the build as u18j left it actually need the font host, or were the forty-five ' +
				'inlined rules already lying around somewhere?',
			build: round.control,
			reading:
				round.control.exitStatus === 0
					? 'the control build came back GREEN with the inliner on, so this round measures nothing about the fetch'
					: 'the control build reached for the font host and died when it could not have it, which is the defect u21 read out of the document, observed',
			establishes:
				'The forty-five inlined `@font-face` rules u21 found in the published document were ' +
				'fetched during the build. They are in no input, they are in no cache the build can ' +
				'reach, and the build cannot be run at all where the font host cannot be.',
		},
		builds: round.builds,
		egressFree,
		determinism: {
			claim:
				'build-23 and build-24 ran the same command over the same bytes with no edit between ' +
				'them, each into a cleaned output directory, under the same egress guard.',
			runs: 2,
			identical,
			files: first.length,
			differingAcrossRuns,
			inventorySha256: sha256(canonical(first)),
			command: round.builds[0]?.command ?? '',
			deterministicModuloClock,
			verdict:
				differingAcrossRuns.length === 0
					? 'Byte-identical across both runs.'
					: `Deterministic modulo ${differingAcrossRuns.join(', ')}, ` +
						`which differs in ${manifestKeysDiffering.join(', ')} and nothing else.`,
			manifestKeysDiffering,
			manifestHashTableIdentical:
				canonical(firstManifest['hashTable']) === canonical(secondManifest['hashTable']),
			ngswClockField:
				'ngsw.json is the file that differs, and it was compared key by key rather than by hash. ' +
				"The generated manifest stamps the build's wall clock into `timestamp`; that is the only " +
				'key whose value moved, and the hashTable — every emitted file with its digest, worker ' +
				'chunks included — is identical between the two runs. This is the same single field u18j ' +
				'recorded across its three runs.',
			sassRandomFiles:
				'None differed BETWEEN this round\'s two runs, which is what u18i and u18j also saw and ' +
				'is not a claim that the instability cannot appear. It did appear ACROSS the supersede ' +
				'boundary, and that is reported under `census` rather than hidden: the main chunk this ' +
				'round emitted is not the one u18j emitted, and the first byte where the two disagree ' +
				'falls inside the confetti `@keyframes …_bang` box-shadow list the era baseline chased ' +
				'the instability to.',
		},
		artifactsEmitted: first.length,
		canonicalRoot: CANONICAL_ROOT,
		repeatedRoot: REPEATED_ROOT,
		inventory: first,
		census: {
			claim:
				'The 62-artifact census u18j published is re-verified in the rebuilt dist, by logical ' +
				'name and by count, and every file whose bytes moved is named.',
			method:
				"u18j's own elision: every `.<hex>` segment of at least eight digits removed from a file " +
				'name wherever it appears, so that a chunk and its map are both recognised across a moved ' +
				'content hash.',
			supersededRoot: SUPERSEDED_ROOT,
			supersededFiles: superseded.length,
			rebuiltFiles: first.length,
			logicalNames: logicalNow.length,
			logicalNamesMatchSuperseded: canonical(logicalNow) === canonical(logicalThen),
			censusHolds,
			byteIdenticalToSuperseded: namesUnchanged.length - changedAgainstSuperseded.length,
			changedAgainstSuperseded,
			renamedAgainstSuperseded: {
				gone: [...supersededDigests.keys()].filter((name) => !firstDigests.has(name)).sort(),
				new: [...firstDigests.keys()].filter((name) => !supersededDigests.has(name)).sort(),
			},
			sassRandomReading:
				sassReading === null
					? 'The main chunk is byte-identical to the superseded one.'
					: {
							supersededChunk: supersededMain?.path ?? null,
							rebuiltChunk: currentMain?.path ?? null,
							firstDifferingByte: sassReading.offset,
							insideBangKeyframes: sassReading.insideBangKeyframes,
							supersededExcerpt: sassReading.leftExcerpt,
							rebuiltExcerpt: sassReading.rightExcerpt,
							reading:
								'The two chunks agree for the whole of their inlined component CSS until the ' +
								'confetti keyframe, and disagree from its first box-shadow literal onward. ' +
								"Sass `random()` is unseeded, so the era baseline's recorded instability is the " +
								'explanation, and the renamed main and runtime files are its consequence: the ' +
								'content hash moves with the literals and the runtime chunk carries the map of ' +
								'chunk ids to filenames.',
						},
			reading:
				'62 files then, 62 files now, the same set of logical names, and the four names that ' +
				'differ are two files and their maps under a moved content hash. Two files changed bytes ' +
				'under an unchanged name — the emitted document, which is what this round set out to ' +
				'change, and the service-worker manifest, which lists the digests of everything else.',
		},
		workerChunks: {
			claim:
				'Both web worker chunks survive the rebuild, byte-identical to the ones u18j measured, ' +
				'still referenced by the emitted runtime and still precached by the emitted manifest.',
			emitted: workerChunks,
			byteIdenticalToSuperseded: workerChunks.every(
				(file) => firstDigests.get(file) === supersededDigests.get(file),
			),
			referencedByRuntime,
			runtimeChunk: runtimeChunk?.path ?? null,
			precachedByServiceWorker: precached,
			hashTableEntries: Object.keys(hashTable).length,
			supersededEmitted: supersededRecord.workerChunks.emitted,
		},
		document: {
			state: 'measured-era-faithful-font-seam',
			sourceIndex: 'src/index.html',
			sourceFontLinks,
			emittedIndex: `${CANONICAL_ROOT}/index.html`,
			emittedFontLinks,
			emittedFontLinksMatchSource,
			entityEscaping:
				'The emitted href writes `&` as `&amp;`, which is the document serialising the same URL ' +
				'and not a different address. The match above is made after that one entity is undone.',
			inlinedFontFaceRules: fontFaceRules(emittedIndex),
			supersededInlinedFontFaceRules: fontFaceRules(supersededIndex),
			preconnectEmitted: emittedIndex.includes('rel="preconnect"'),
			supersededPreconnectEmitted: supersededIndex.includes('rel="preconnect"'),
			reading:
				"The emitted document links the same Roboto stylesheet the application's own source " +
				'links, and carries no `@font-face` rule and no preconnect the builder minted. The ' +
				'superseded document carried forty-five inlined rules and a preconnect to ' +
				'`fonts.gstatic.com`, neither of which appears in any input.',
		},
		supersedes: {
			record: SUPERSEDED_RECORD,
			unit: 'lrapr-t006/u18j-worker-chunks-parity',
			by: 'reference',
			bytesSha256: sha256(supersededBytes),
			why:
				"u18j's bytes are unchanged and it remains the record of what it measured: the round that " +
				"closed this cell's build story, with both web workers emitted as chunks the runtime " +
				'references and the service worker precaches, and logical-name parity against the era ' +
				'lane stated with every asymmetry named. What it could not see is that the document it ' +
				'published had been assembled with help from a third party. This record replaces it as ' +
				'the migrated lane of this cell, because this is the lane whose bytes are a function of ' +
				'its declared inputs. One file differs from the tree u18j built, and it is the workspace.',
			carriesForward:
				'Every claim u18j made about the workers, the accommodation bill and logical-name parity ' +
				'against the era lane is carried forward unchanged and unre-measured here, except the ' +
				'worker claim, which this record re-verifies against the rebuilt dist.',
		},
		notEstablished: [
			'The guard is process-scoped. It establishes what these build processes attempted; it does ' +
				'not establish that the machine was offline, and it says nothing about any other process.',
			'Nothing here establishes that this application makes no other undeclared request. It ' +
				'establishes that these three builds made exactly the attempts recorded above.',
			'The runtime request the era build made and this lane restores is still a request. Nothing ' +
				'here loaded the emitted document in a browser, so nothing here establishes what that ' +
				'request does or what the page looks like when it is refused.',
			'No witness work was done in this round by design. Whether the application runs, mounts or ' +
				'keeps what a user types is not established here and is not re-established from u18j, ' +
				'which did not establish it either.',
			'Logical-name parity against the ERA lane is not re-measured here. It is u18j\'s reading, of ' +
				'a build whose only difference from this one is the emitted document, the manifest and ' +
				'the confetti literals.',
			'The Sass instability is attributed from the first differing byte of one pair of chunks. ' +
				'That is a reading of two files, not a proof that no other cause contributed to the ' +
				'moved content hash.',
			'The era lane was not rebuilt, re-measured or touched by this round.',
		],
		recordedRisks: [
			'The two remaining Angular 16 lanes on the u21 rebuild list are unaffected by this defect ' +
				'per u21, and nothing here re-checks that reading.',
			'The service-worker manifest lists the digest of every emitted file, so any future round ' +
				'that changes one byte of one bundle changes ngsw.json too. A reader comparing lanes ' +
				'should expect that file to move whenever anything else does.',
			'`.angular/cache` was not cleared between the builds of this round. That the two runs agree ' +
				'is therefore consistent with both a deterministic pipeline and a warm cache, and the ' +
				'Sass literals moving across the supersede boundary is the reason to say so out loud.',
			'The 19 manual-migration-steps and the one accommodation payload file u18h recorded are ' +
				'still in this lane, untouched and un-re-measured by this round.',
		],
	});
}

export async function main(): Promise<void> {
	const record = verifySealedRecord(await buildFontLaneRecord());
	await mkdir(EVIDENCE_DIRECTORY, { recursive: true });
	const bytes = canonical(record);
	await writeFile(path.join(EVIDENCE_DIRECTORY, FONT_LANE_FILE), bytes);
	process.stdout.write(
		`font lane ${String(record['result'])}, digest ${record.digest.slice(0, 12)}, ` +
			`bytes sha256 ${sha256(bytes)}\n`,
	);
}

if (process.argv[1]?.endsWith('angular-super-productivity-u23-font-record.ts'))
	main().catch((error: unknown) => {
		process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
		process.exitCode = 1;
	});
