import { access, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { basename, join, relative, resolve } from 'pathe';
import { canonicalize, sha256 } from '../../../core/src/receipts/canonicalize.ts';
import {
	parseWitnessReactLinkfreeReceipt,
	REACT_LINKFREE_CANONICAL_DIGEST,
	REACT_LINKFREE_FIXTURE,
	REACT_LINKFREE_RECEIPT_PATH,
	REACT_LINKFREE_RECEIPT_SHA256,
	REACT_LINKFREE_SOURCE,
	renderWitnessReactLinkfreeReceipt,
	WITNESS_REACT_LINKFREE_CONSOLE_ERRORS,
	WITNESS_REACT_LINKFREE_CORPUS_RULING,
	WITNESS_REACT_LINKFREE_FAILED_REQUESTS,
	WITNESS_REACT_LINKFREE_MOCKED_SEAMS,
	WITNESS_REACT_LINKFREE_ROUTES,
	WITNESS_REACT_LINKFREE_SCHEMA,
	WITNESS_REACT_LINKFREE_STYLE_PROBES,
	witnessReactLinkfreeBehaviorDigest,
	witnessReactLinkfreeDigest,
	witnessReactLinkfreeRawDigest,
	type WitnessReactLinkfreeMutation,
	type WitnessReactLinkfreeReceipt,
	type WitnessReactLinkfreeRun,
} from '../../../core/src/receipts/witness-react-linkfree.ts';
import {
	stageLinkfreeWitnessLane,
	type LinkfreeStagedCorpus,
} from '../fixture/react-linkfree-v0-72-0-witness-corpus.ts';
import {
	bindReactLinkfreeStaging,
	executeReactLinkfreeWitnessRun,
	LINKFREE_MUTATION_SEAM,
} from './real-app-run.ts';
import {
	assertLinkedWitnessProvenanceEquivalent,
	verifyLinkedWitnessProvenance,
} from './provenance.ts';

const root = resolve(import.meta.dirname, '../../../..');
const fixtureEvidence = join(root, 'evidence/runs/react-linkfree-v0-72-0');
const witnessEvidence = join(root, 'evidence/runs/witness-react-linkfree-v0-72-0');
const stageRoot = join(root, '.versionless/stage/witness-react-linkfree-v0-72-0');
const workRoot = join(root, '.versionless/work/react-linkfree-v0-72-0');
const buildOutputs = {
	baseline: join(workRoot, 'baseline/build-run1'),
	migrated: join(workRoot, 'target/build-vite-run1'),
} as const;
/** The application's own codegen prebuild, taken from the restored source tree. */
const codegenScript = join(workRoot, 'target/generate.js');

async function exists(path: string): Promise<boolean> {
	return access(path).then(
		() => true,
		() => false,
	);
}

async function files(directory: string): Promise<string[]> {
	const output: string[] = [];
	for (const entry of await readdir(directory, { withFileTypes: true })) {
		const path = join(directory, entry.name);
		if (entry.isDirectory()) output.push(...(await files(path)));
		else if (entry.isFile()) output.push(path);
	}
	return output.sort();
}

/**
 * Stage both lanes for the browser proof.
 *
 * Each lane is the committed build output with its profile corpus replaced by
 * the synthetic one and its index regenerated by the application's own
 * `generate.js`. The staging proves, per lane, that no bundler-authored byte
 * moved: only the dataset did.
 */
async function stageInputs(): Promise<{
	lanes: Record<'baseline' | 'migrated', string>;
	staged: Record<'baseline' | 'migrated', LinkfreeStagedCorpus>;
}> {
	const lanes = { baseline: join(stageRoot, 'lanes/baseline'), migrated: join(stageRoot, 'lanes/migrated') };
	const staged: Record<'baseline' | 'migrated', LinkfreeStagedCorpus> = {} as Record<
		'baseline' | 'migrated',
		LinkfreeStagedCorpus
	>;
	for (const lane of ['baseline', 'migrated'] as const) {
		if (!(await exists(buildOutputs[lane])))
			throw new Error(`LinkFree ${lane} production output is absent`);
		staged[lane] = await stageLinkfreeWitnessLane({
			repositoryRoot: root,
			buildRoot: buildOutputs[lane],
			laneRoot: lanes[lane],
			codegenScript,
			scratchRoot: join(stageRoot, 'codegen', lane),
		});
	}
	if (
		staged.baseline.corpus.aggregateSha256 !== staged.migrated.corpus.aggregateSha256 ||
		staged.baseline.generatedIndex.sha256 !== staged.migrated.generatedIndex.sha256
	)
		throw new Error('LinkFree lanes were staged with different synthetic corpora');
	bindReactLinkfreeStaging(staged.migrated);
	return { lanes, staged };
}

async function executeRuns(
	lanes: Record<'baseline' | 'migrated', string>,
): Promise<WitnessReactLinkfreeRun[]> {
	const runs: WitnessReactLinkfreeRun[] = [];
	for (const lane of ['baseline', 'migrated'] as const)
		for (const pass of [1, 2] as const) {
			const raw = await executeReactLinkfreeWitnessRun({
				lane,
				pass,
				laneRoot: lanes[lane],
				receiptRoot: join(stageRoot, 'receipts'),
			});
			const run = raw as WitnessReactLinkfreeRun;
			if (run.semanticDigest !== witnessReactLinkfreeRawDigest(run))
				throw new Error(`LinkFree ${lane} pass ${String(pass)} raw digest differs`);
			runs.push({ ...run, behaviorDigest: witnessReactLinkfreeBehaviorDigest(run) });
		}
	if (new Set(runs.map((run) => run.behaviorDigest)).size !== 1)
		throw new Error('LinkFree baseline/migrated behavior parity differs');
	return runs;
}

/**
 * Byte mutation on the migrated build: locate the visible not-found text in the
 * served module, overwrite it in place with an equal-length filler, require the
 * journey to go red on that exact assertion, restore the original bytes, and
 * require the restored journey to reproduce the parity behavior digest.
 */
async function semanticMutation(
	laneRoot: string,
	behaviorDigest: string,
): Promise<WitnessReactLinkfreeMutation> {
	const expected = Buffer.from(LINKFREE_MUTATION_SEAM);
	const candidates: Array<{ path: string; offset: number }> = [];
	for (const path of await files(laneRoot)) {
		const bytes = await readFile(path);
		const offset = bytes.indexOf(expected);
		if (offset < 0) continue;
		if (bytes.lastIndexOf(expected) !== offset)
			throw new Error('LinkFree semantic seam is not unique within its file');
		candidates.push({ path, offset });
	}
	const modules = candidates.filter((candidate) => candidate.path.endsWith('.js'));
	const target = modules[0];
	if (
		modules.length !== 1 ||
		target === undefined ||
		canonicalize(candidates.map((candidate) => candidate.path).sort()) !==
			canonicalize([target.path, `${target.path}.map`].sort())
	)
		throw new Error('LinkFree semantic seam is not a single served module and its sourcemap');
	const before = await readFile(target.path);
	const mutated = Buffer.from(before);
	Buffer.alloc(expected.length, 'X').copy(mutated, target.offset);
	const beforeSha256 = sha256(before);
	const mutatedSha256 = sha256(mutated);
	let intendedFailure = false;
	try {
		await writeFile(target.path, mutated);
		try {
			await executeReactLinkfreeWitnessRun({
				lane: 'migrated',
				pass: 1,
				laneRoot,
				receiptRoot: join(stageRoot, 'mutation-receipt'),
			});
		} catch (error) {
			const message = error instanceof Error ? error.message : String(error);
			intendedFailure = message.includes(LINKFREE_MUTATION_SEAM);
		}
	} finally {
		await writeFile(target.path, before);
	}
	const afterRestoreSha256 = sha256(await readFile(target.path));
	if (!intendedFailure || afterRestoreSha256 !== beforeSha256)
		throw new Error('LinkFree semantic mutation was not exact red and byte-restored');
	const restored = (await executeReactLinkfreeWitnessRun({
		lane: 'migrated',
		pass: 1,
		laneRoot,
		receiptRoot: join(stageRoot, 'restoration-receipt'),
	})) as WitnessReactLinkfreeRun;
	const restoredBehaviorDigest = witnessReactLinkfreeBehaviorDigest(restored);
	if (restoredBehaviorDigest !== behaviorDigest)
		throw new Error('LinkFree restored browser behavior differs');
	return {
		failure: 'witness-semantic-assertion',
		intendedFailure: true,
		lane: 'migrated',
		seam: LINKFREE_MUTATION_SEAM,
		path: relative(laneRoot, target.path),
		offset: target.offset,
		beforeSha256,
		mutatedSha256,
		afterRestoreSha256,
		restoredByteIdentically: true,
		restoredRun: 'pass',
		restoredBehaviorDigest,
	};
}

export async function runWitnessReactLinkfree(): Promise<WitnessReactLinkfreeReceipt> {
	if (
		process.env.VERSIONLESS_NETWORK_MODE !== 'offline' ||
		process.env.NPM_CONFIG_OFFLINE !== 'true'
	)
		throw new Error('LinkFree Witness requires dual offline controls');
	if (await exists(witnessEvidence)) throw new Error('LinkFree Witness output collision');
	const provenance = await verifyLinkedWitnessProvenance(root);
	const canonicalBytes = await readFile(join(root, REACT_LINKFREE_RECEIPT_PATH));
	const canonical = JSON.parse(canonicalBytes.toString('utf8')) as {
		fixture?: unknown;
		integrity: { canonicalDigest: string };
	};
	if (
		canonical.fixture !== REACT_LINKFREE_FIXTURE ||
		canonical.integrity.canonicalDigest !== REACT_LINKFREE_CANONICAL_DIGEST ||
		sha256(canonicalBytes) !== REACT_LINKFREE_RECEIPT_SHA256
	)
		throw new Error('LinkFree canonical build receipt identity differs');
	const { lanes, staged } = await stageInputs();
	const runs = await executeRuns(lanes);
	const mutation = await semanticMutation(lanes.migrated, runs[0]!.behaviorDigest);
	const artifacts = join(fixtureEvidence, 'artifacts');
	await mkdir(artifacts, { recursive: true });
	await writeFile(join(artifacts, 'witness-journeys.json'), `${canonicalize(runs)}\n`, {
		flag: 'wx',
	});
	await writeFile(join(artifacts, 'witness-mutation.json'), `${canonicalize(mutation)}\n`, {
		flag: 'wx',
	});
	await writeFile(
		join(artifacts, 'witness-synthetic-corpus.json'),
		`${canonicalize({ ruling: WITNESS_REACT_LINKFREE_CORPUS_RULING, staged })}\n`,
		{ flag: 'wx' },
	);
	const receipt: WitnessReactLinkfreeReceipt = {
		schemaVersion: WITNESS_REACT_LINKFREE_SCHEMA,
		result: 'pass',
		fixture: REACT_LINKFREE_FIXTURE,
		source: REACT_LINKFREE_SOURCE,
		provenance,
		canonicalReceipt: {
			path: REACT_LINKFREE_RECEIPT_PATH,
			canonicalDigest: canonical.integrity.canonicalDigest,
			sha256: sha256(canonicalBytes),
		},
		corpusRuling: WITNESS_REACT_LINKFREE_CORPUS_RULING,
		stagedCorpus: {
			policy: staged.migrated.policy,
			replacedPaths: staged.migrated.replacedPaths,
			bundlerAuthoredPaths: staged.migrated.bundlerAuthoredPaths,
			bundlerAuthoredBytesUnchanged: true,
		},
		runs,
		mutation,
		consoleErrors: WITNESS_REACT_LINKFREE_CONSOLE_ERRORS,
		failedRequests: WITNESS_REACT_LINKFREE_FAILED_REQUESTS,
		mockedSeams: WITNESS_REACT_LINKFREE_MOCKED_SEAMS,
		renderedStyleParity: {
			state: 'measured-identical-resolved-styles',
			probes: WITNESS_REACT_LINKFREE_STYLE_PROBES.length,
			lanesAgree: true,
			note: 'the baseline ships the stylesheet its own postbuild purge cut by 91.8% and the migrated lane ships that stylesheet unpurged, and the two still resolve to identical appearance at every probe',
		},
		scrollSurface: runs[0]!.scrollSurface,
		router: {
			library: 'react-router-dom-5',
			routes: [...WITNESS_REACT_LINKFREE_ROUTES],
			dynamicSegment: '/:username',
			navigations: WITNESS_REACT_LINKFREE_ROUTES.length,
		},
		readiness: {
			reactLineage: { ready: 1, total: 4, counted: false },
			overall: { ready: 3, total: 12 },
		},
		locality: { mode: 'offline', successfulNonLoopback: 0, osWideIsolation: false },
		nonclaims: [
			'This is one React lineage under direct Witness and does not establish generic React or create-react-app 5 support.',
			'The React lineage readiness score is unchanged; this vertical is not counted before Judge audit.',
			'The dataset is SYNTHETIC. These journeys prove the behaviour of the application, not the correctness, completeness or rendering of the 561 real contributor profiles its archive ships. Nothing here is evidence about that dataset, and none of it was rendered, quoted or published.',
			'The profile route the not-found journey reaches is the example the application itself hard-codes on its homepage. It names a real person, so it is recorded through a closed-list redaction; the route shape is evidence, the identity is not.',
			'Scroll is claimed only for the profile route, the one stage the journey exercised with a real wheel gesture. Three of the five measured stages overflow the 1280x720 viewport; the other two that overflow were measured and left unscrolled, and no scroll coverage is claimed for them.',
			'Drag is not tested because the visited routes have no genuine drag surface.',
			'Both avatar hosts are answered inside the browser context and neither is contacted. The fallback image is a deterministic placeholder, not what the third-party generator would have returned, and no claim is made about that service.',
			'The declared outbound links on every synthetic profile are unresolvable by construction and are never fetched; no claim is made about link behaviour beyond the list the application renders.',
			'The upstream cypress suite was not run. Its four features documented which journeys matter and this proof drives all four, but it is not that suite and does not stand in for it.',
			'Locality is process-scoped and does not establish operating-system-wide isolation.',
			'Receipts prove reproducibility and hash integrity, not certification, authenticity, signer identity, compliance, or an earned SLSA level.',
		],
		integrity: { algorithm: 'sha256', canonicalDigest: '' },
	};
	receipt.integrity.canonicalDigest = witnessReactLinkfreeDigest(receipt);
	parseWitnessReactLinkfreeReceipt(receipt);
	await mkdir(witnessEvidence, { recursive: true });
	await writeFile(join(witnessEvidence, 'receipt.json'), `${canonicalize(receipt)}\n`, {
		flag: 'wx',
	});
	await writeFile(
		join(witnessEvidence, 'receipt.md'),
		renderWitnessReactLinkfreeReceipt(receipt),
		{ flag: 'wx' },
	);
	return receipt;
}

export async function verifyWitnessReactLinkfree(
	output = witnessEvidence,
): Promise<WitnessReactLinkfreeReceipt> {
	const expectedProvenance = await verifyLinkedWitnessProvenance(root);
	const receipt = parseWitnessReactLinkfreeReceipt(
		JSON.parse(await readFile(join(output, 'receipt.json'), 'utf8')),
	);
	assertLinkedWitnessProvenanceEquivalent(receipt.provenance, expectedProvenance, "LinkFree");
	const canonicalBytes = await readFile(join(root, receipt.canonicalReceipt.path));
	if (sha256(canonicalBytes) !== receipt.canonicalReceipt.sha256)
		throw new Error('LinkFree canonical receipt bytes drifted');
	if (
		(await readFile(join(output, 'receipt.md'), 'utf8')) !==
		renderWitnessReactLinkfreeReceipt(receipt)
	)
		throw new Error('LinkFree human Witness receipt differs');
	const serialized = canonicalize(receipt);
	if (serialized.includes(root) || serialized.includes(process.env.USER ?? ''))
		throw new Error('LinkFree receipt leaks host identity');
	return receipt;
}

export async function main(args = process.argv.slice(2)): Promise<void> {
	const publishIndex = args.indexOf('--publish');
	const verifyIndex = args.indexOf('--verify');
	if (args.includes('--run-twice') && publishIndex >= 0 && args[publishIndex + 1]) {
		const output = resolve(root, args[publishIndex + 1]!);
		if (output !== witnessEvidence) throw new Error('LinkFree publish path differs');
		const receipt = await runWitnessReactLinkfree();
		process.stdout.write(
			`${canonicalize({ result: receipt.result, digest: receipt.integrity.canonicalDigest })}\n`,
		);
		return;
	}
	if (verifyIndex >= 0 && args[verifyIndex + 1]) {
		const receipt = await verifyWitnessReactLinkfree(resolve(root, args[verifyIndex + 1]!));
		process.stdout.write(
			`${canonicalize({ result: receipt.result, digest: receipt.integrity.canonicalDigest })}\n`,
		);
		return;
	}
	throw new Error('LinkFree Witness runner requires --run-twice --publish <dir> or --verify <dir>');
}

if (basename(process.argv[1] ?? '') === 'react-linkfree-run.ts')
	main().catch((error: unknown) => {
		process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
		process.exitCode = 1;
	});
